version: '3'
services:
  uniswap-pairs-postgres:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=uniswap-pairs
  app:
    build: .
    depends_on:
      - uniswap-pairs-postgres
    command: npm start